var namespaceqpp =
[
    [ "atom", "classqpp_1_1atom.html", "classqpp_1_1atom" ],
    [ "attributes", "structqpp_1_1attributes.html", null ],
    [ "attributes< bool >", "structqpp_1_1attributes_3_01bool_01_4.html", "structqpp_1_1attributes_3_01bool_01_4" ],
    [ "attributes< double >", "structqpp_1_1attributes_3_01double_01_4.html", "structqpp_1_1attributes_3_01double_01_4" ],
    [ "attributes< float >", "structqpp_1_1attributes_3_01float_01_4.html", "structqpp_1_1attributes_3_01float_01_4" ],
    [ "attributes< int >", "structqpp_1_1attributes_3_01int_01_4.html", "structqpp_1_1attributes_3_01int_01_4" ],
    [ "bonding_table", "classqpp_1_1bonding__table.html", "classqpp_1_1bonding__table" ],
    [ "generalized_cell", "structqpp_1_1generalized__cell.html", "structqpp_1_1generalized__cell" ],
    [ "generated_group", "classqpp_1_1generated__group.html", "classqpp_1_1generated__group" ],
    [ "generators_pack", "classqpp_1_1generators__pack.html", "classqpp_1_1generators__pack" ],
    [ "geometry", "classqpp_1_1geometry.html", "classqpp_1_1geometry" ],
    [ "geometry_observer", "structqpp_1_1geometry__observer.html", "structqpp_1_1geometry__observer" ],
    [ "group_analyzer", "classqpp_1_1group__analyzer.html", "classqpp_1_1group__analyzer" ],
    [ "group_characters", "classqpp_1_1group__characters.html", "classqpp_1_1group__characters" ],
    [ "index", "classqpp_1_1index.html", "classqpp_1_1index" ],
    [ "iterator", "classqpp_1_1iterator.html", "classqpp_1_1iterator" ],
    [ "matrix2d", "classqpp_1_1matrix2d.html", "classqpp_1_1matrix2d" ],
    [ "matrix3d", "classqpp_1_1matrix3d.html", "classqpp_1_1matrix3d" ],
    [ "molecule", "classqpp_1_1molecule.html", "classqpp_1_1molecule" ],
    [ "neighbours_table", "classqpp_1_1neighbours__table.html", "classqpp_1_1neighbours__table" ],
    [ "numeric_type", "structqpp_1_1numeric__type.html", null ],
    [ "numeric_type< double >", "structqpp_1_1numeric__type_3_01double_01_4.html", "structqpp_1_1numeric__type_3_01double_01_4" ],
    [ "numeric_type< float >", "structqpp_1_1numeric__type_3_01float_01_4.html", "structqpp_1_1numeric__type_3_01float_01_4" ],
    [ "numeric_type< int >", "structqpp_1_1numeric__type_3_01int_01_4.html", "structqpp_1_1numeric__type_3_01int_01_4" ],
    [ "numeric_type< long double >", "structqpp_1_1numeric__type_3_01long_01double_01_4.html", "structqpp_1_1numeric__type_3_01long_01double_01_4" ],
    [ "numeric_type< std::complex< double > >", "structqpp_1_1numeric__type_3_01std_1_1complex_3_01double_01_4_01_4.html", "structqpp_1_1numeric__type_3_01std_1_1complex_3_01double_01_4_01_4" ],
    [ "numeric_type< std::complex< float > >", "structqpp_1_1numeric__type_3_01std_1_1complex_3_01float_01_4_01_4.html", "structqpp_1_1numeric__type_3_01std_1_1complex_3_01float_01_4_01_4" ],
    [ "numeric_type< std::complex< long double > >", "structqpp_1_1numeric__type_3_01std_1_1complex_3_01long_01double_01_4_01_4.html", "structqpp_1_1numeric__type_3_01std_1_1complex_3_01long_01double_01_4_01_4" ],
    [ "periodic_cell", "structqpp_1_1periodic__cell.html", "structqpp_1_1periodic__cell" ],
    [ "py_2indexed_property", "structqpp_1_1py__2indexed__property.html", "structqpp_1_1py__2indexed__property" ],
    [ "py_indexed_property", "structqpp_1_1py__indexed__property.html", "structqpp_1_1py__indexed__property" ],
    [ "rotrans", "structqpp_1_1rotrans.html", "structqpp_1_1rotrans" ],
    [ "shape", "classqpp_1_1shape.html", "classqpp_1_1shape" ],
    [ "shape_box", "classqpp_1_1shape__box.html", "classqpp_1_1shape__box" ],
    [ "shape_intersect", "classqpp_1_1shape__intersect.html", "classqpp_1_1shape__intersect" ],
    [ "shape_invert", "classqpp_1_1shape__invert.html", "classqpp_1_1shape__invert" ],
    [ "shape_sphere", "classqpp_1_1shape__sphere.html", "classqpp_1_1shape__sphere" ],
    [ "shape_subtract", "classqpp_1_1shape__subtract.html", "classqpp_1_1shape__subtract" ],
    [ "shape_union", "classqpp_1_1shape__union.html", "classqpp_1_1shape__union" ],
    [ "shape_xor", "classqpp_1_1shape__xor.html", "classqpp_1_1shape__xor" ],
    [ "simple_vector", "classqpp_1_1simple__vector.html", "classqpp_1_1simple__vector" ],
    [ "tokenizer", "classqpp_1_1tokenizer.html", "classqpp_1_1tokenizer" ],
    [ "translation", "structqpp_1_1translation.html", "structqpp_1_1translation" ],
    [ "vector2d", "classqpp_1_1vector2d.html", "classqpp_1_1vector2d" ],
    [ "vector3d", "classqpp_1_1vector3d.html", "classqpp_1_1vector3d" ]
];